package constants

const (
	ERR_INVALID_REQUEST = "ERR_INVALID_REQUEST"
	ERR_INVALID_PASSWORD_INSECURE = "ERR_INVALID_PASSWORD_INSECURE"

	ERR_USER_INVALID_CREDENTIALS = "ERR_USER_INVALID_CREDENTIALS"
	ERR_USER_INACTIVE = "ERR_USER_INACTIVE"
)
