package constants

const (
	ERR_INVALID_REQUEST = "ERR_INVALID_REQUEST"
	ERR_INVALID_PASSWORD_INSECURE = "ERR_INVALID_PASSWORD_INSECURE"
	ERR_INVALID_PHONE_NUMBER = "ERR_INVALID_PHONE_NUMBER"

	ERR_USER_INVALID_CREDENTIALS = "ERR_USER_INVALID_CREDENTIALS"
	ERR_USER_INACTIVE = "ERR_USER_INACTIVE"

	ERR_AUTH_EMPTY_JWT_CREDENTIALS = "ERR_AUTH_EMPTY_JWT_CREDENTIALS"
	ERR_AUTH_CANNOT_AUTHORIZE = "ERR_AUTH_CANNOT_AUTHORIZE"
	ERR_AUTH_CANNOT_CREATE_TEMPORARY_PASSWORD = "ERR_AUTH_CANNOT_CREATE_TEMPORARY_PASSWORD"

	ERR_RESET_PASSWORD_INVALID_CODE = "ERR_RESET_PASSWORD_INVALID_CODE"
	ERR_RESET_PASSWORD_EXPIRED_CODE = "ERR_RESET_PASSWORD_EXPIRED_CODE"
	ERR_RESET_CANNOT_RECREATE_PASSWORD = "ERR_RESET_CANNOT_RECREATE_PASSWORD"

	ERR_FAILED_SEND_MAIL = "ERR_FAILED_SEND_MAIL"

	ERR_CLIENT_ADVISOR_EXISTS = "ERR_CLIENT_ADVISOR_EXISTS"
)
