package constants

const (
	PORTFOLIO_STATUS_NEW = "PORTFOLIO_STATUS_NEW"
	PORTFOLIO_STATUS_REQUEST_OPTIMIZATION = "PORTFOLIO_STATUS_REQUEST_OPTIMIZATION"
	PORTFOLIO_STATUS_OPTIMIZATION_FINISHED = "PORTFOLIO_STATUS_OPTIMIZATION_FINISHED"
	PORTFOLIO_STATUS_CLOSED = "PORTFOLIO_STATUS_CLOSED"

	PORTFOLIO_STATE_DRAFT = "PORTFOLIO_STATE_DRAFT"
	PORTFOLIO_STATE_CURRENT = "PORTFOLIO_STATE_CURRENT"
	PORTFOLIO_STATE_EDITING = "PORTFOLIO_STATE_EDITING"

	PORTFOLIO_CHANGES_ROW_CREATED = "CREATED"
	PORTFOLIO_CHANGES_ROW_DELETED = "DELETED"
	PORTFOLIO_CHANGES_ROW_UPDATED = "UPDATED"
)
