package constants

const (
	PORTFOLIO_STATUS_REQUEST_OPTIMIZATION = "REQUEST_OPTIMIZATION"
	PORTFOLIO_STATUS_OPTIMIZATION_PENDING = "OPTIMIZATION_PENDING"
	PORTFOLIO_STATUS_OPTIMIZATION_FINISHED = "OPTIMIZATION_FINISHED"
	PORTFOLIO_STATUS_CLOSED = "CLOSED"

	PORTFOLIO_STATE_DRAFT = "DRAFT"
	PORTFOLIO_STATE_CURRENT = "CURRENT"
	PORTFOLIO_STATE_EDITING = "EDITING"

)
