package constants

const (
	USER_STATUS_ACTIVE = "USER_STATUS_ACTIVE"
	USER_STATUS_RESET_PASSWORD_CODE_SENT = "USER_STATUS_RESET_PASSWORD_CODE_SENT"
	USER_STATUS_AWAIT_APPROVE = "USER_STATUS_AWAIT_APPROVE"

	USER_ROLE_CLIENT = "CLIENT"
	USER_ROLE_ADVISOR = "ADVISOR"
	USER_ROLE_ADMIN = "ADMIN"
	USER_ROLE_SUPERADMIN = "SUPERADMIN"
)

